# Generated by Django 6.0.2 on 2026-02-17 11:26

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('manager_name', models.CharField(max_length=32)),
                ('grade', models.CharField()),
                ('position', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('history', models.TextField()),
                ('capabilities', models.TextField()),
                ('apsirations', models.TextField()),
                ('next_move', models.TextField()),
                ('mobility', models.TextField()),
                ('succession', models.CharField()),
                ('successor', models.CharField(max_length=32)),
                ('estimated_grade', models.CharField()),
                ('dev_cell_rating', models.CharField()),
                ('performance_rating', models.CharField()),
                ('review_date', models.DateField()),
                ('mentor', models.CharField(max_length=32)),
                ('mentee', models.CharField(max_length=32)),
                ('wants', models.TextField()),
                ('needs', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dc_main.individual')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('dc_main.individual',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
