from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Quorom(models.Model):
    Username = models.ForeignKey(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=16)
    Manager = models.CharField(max_length=16)
    # Photo = models.ImageField(upload_to='photos/')
    Grade = models.CharField(max_length=16)
    Position = models.CharField(max_length=16)
    Location = models.CharField(max_length=16)
    History = models.TextField(max_length=256)
    Capabilities_and_Attributes = models.TextField(max_length=256)
    Career_Aspiractions = models.TextField(max_length=256)
    Development_Needs = models.TextField(max_length=256)
    Next_Move = models.TextField(max_length=128)
    Mobility = models.TextField(max_length=128)
    Succession_Plan = models.TextField(max_length=256)
    Successor = models.CharField(max_length=32)
    Potential_Grade = models.CharField(max_length=16)
    Dev_Cell_Rating = models.CharField(max_length=16)
    Performance_Rating = models.CharField(max_length=16)
    Review_Date = models.DateField(max_length=16)
    Mentor = models.CharField(max_length=16)
    Mentee = models.CharField(max_length=16)
    Wants = models.TextField(max_length=256)
    Needs = models.TextField(max_length=256)
    Acion_Owner = models.CharField(max_length=16)
    Action_Status = models.CharField(max_length=32)
    Action = models.CharField(max_length=16)
    Review_Information = models.TextField(max_length=32)

class Manager(models.Model):
    Username = models.ForeignKey(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=16)
    Manager = models.CharField(max_length=16)
    # Photo = models.ImageField(upload_to='photos/')
    Grade = models.CharField(max_length=16)
    Position = models.CharField(max_length=16)
    Location = models.CharField(max_length=16)
    History = models.TextField(max_length=256)
    Capabilities_and_Attributes = models.TextField(max_length=256)
    Career_Aspiractions = models.TextField(max_length=256)
    Development_Needs = models.TextField(max_length=256)
    Next_Move = models.TextField(max_length=128)
    Mobility = models.TextField(max_length=128)
    Succession_Plan = models.TextField(max_length=256)
    Successor = models.CharField(max_length=32)
    Potential_Grade = models.CharField(max_length=16)
    Dev_Cell_Rating = models.CharField(max_length=16)
    Performance_Rating = models.CharField(max_length=16)
    Review_Date = models.DateField(max_length=16)
    Mentor = models.CharField(max_length=16)
    Mentee = models.CharField(max_length=16)
    Wants = models.TextField(max_length=256)
    Needs = models.TextField(max_length=256)
    Acion_Owner = models.CharField(max_length=16)
    Action_Status = models.CharField(max_length=32)
    Action = models.CharField(max_length=16)
    Review_Information = models.TextField(max_length=32)

class Engineer(models.Model):
    Username = models.ForeignKey(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=16)
    Manager = models.CharField(max_length=16)
    # Photo = models.ImageField(upload_to='photos/')
    Grade = models.CharField(max_length=16)
    Position = models.CharField(max_length=16)
    Location = models.CharField(max_length=16)
    History = models.TextField(max_length=256)
    Capabilities_and_Attributes = models.TextField(max_length=256)
    Career_Aspiractions = models.TextField(max_length=256)
    Development_Needs = models.TextField(max_length=256)
    Next_Move = models.TextField(max_length=128)
    Mobility = models.TextField(max_length=128)
    Succession_Plan = models.TextField(max_length=256)
    Successor = models.CharField(max_length=32)
    Potential_Grade = models.CharField(max_length=16)
    Dev_Cell_Rating = models.CharField(max_length=16)
    Performance_Rating = models.CharField(max_length=16)
    Review_Date = models.DateField(max_length=16)
    Mentor = models.CharField(max_length=16)
    Mentee = models.CharField(max_length=16)
    Wants = models.TextField(max_length=256)
    Needs = models.TextField(max_length=256)
    Acion_Owner = models.CharField(max_length=16)
    Action_Status = models.CharField(max_length=32)
    Action = models.CharField(max_length=16)
    Review_Information = models.TextField(max_length=32)

class Administrator(models.Model):
    Username = models.ForeignKey(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=16)
    Manager = models.CharField(max_length=16)
    # Photo = models.ImageField(upload_to='photos/')
    Grade = models.CharField(max_length=16)
    Position = models.CharField(max_length=16)
    Location = models.CharField(max_length=16)
    History = models.TextField(max_length=256)
    Capabilities_and_Attributes = models.TextField(max_length=256)
    Career_Aspiractions = models.TextField(max_length=256)
    Development_Needs = models.TextField(max_length=256)
    Next_Move = models.TextField(max_length=128)
    Mobility = models.TextField(max_length=128)
    Succession_Plan = models.TextField(max_length=256)
    Successor = models.CharField(max_length=32)
    Potential_Grade = models.CharField(max_length=16)
    Dev_Cell_Rating = models.CharField(max_length=16)
    Performance_Rating = models.CharField(max_length=16)
    Review_Date = models.DateField(max_length=16)
    Mentor = models.CharField(max_length=16)
    Mentee = models.CharField(max_length=16)
    Wants = models.TextField(max_length=256)
    Needs = models.TextField(max_length=256)
    Acion_Owner = models.CharField(max_length=16)
    Action_Status = models.CharField(max_length=32)
    Action = models.CharField(max_length=16)
    Review_Information = models.TextField(max_length=32)